version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=Pikachu1@user
      - RABBITMQ_DEFAULT_PASS=Pikachu1@pass

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=db_Pikachu
      - MYSQL_USER=Pikachu1@user
      - MYSQL_PASSWORD=Pikachu1@pass
